# Tensorflow Basic Syntax

In [1]:
import tensorflow as tf

AttributeError: module 'tensorflow' has no attribute '_version_'

## Constant
"TensorFlow, as the name indicates, is a framework to define and run computations involving tensors. A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

When writing a TensorFlow program, the main object you manipulate and pass around is the tf.Tensor. A tf.Tensor object represents a partially defined computation that will eventually produce a value. TensorFlow programs work by first building a graph of tf.Tensor objects, detailing how each tensor is computed based on the other available tensors and then by running parts of this graph to achieve the desired results."

In [5]:
hello = tf.constant("hello")

In [6]:
world = tf.constant("world")

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'helloworld'


In [12]:
temp1= tf.fill((4,4),10)

In [13]:
temp2=tf.ones((4,4))

In [14]:
temp3=tf.zeros((4,4))

In [16]:
temp4=tf.random_normal((4,4),mean=0,stddev=1)

In [17]:
temp5=tf.random_uniform((4,4),minval=0,maxval=1)

In [19]:
ops = [temp1,temp2,temp3,temp4,temp5]

In [22]:
with tf.Session() as sess:
    for op in ops:
        print(str(op.eval()))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[-1.18527174  0.78345567 -0.65617865 -1.21309447]
 [-1.12924469  1.98927367 -0.92752665 -0.71711761]
 [ 1.52234471 -1.9752754  -0.32903776  0.37486106]
 [-0.43934497 -0.1055171  -0.0843417  -1.70713151]]
[[ 0.61049151  0.10603797  0.14676261  0.56810343]
 [ 0.44006717  0.45509946  0.94830608  0.35410655]
 [ 0.49507177  0.55659091  0.96754372  0.44245613]
 [ 0.0476687   0.16881001  0.52943039  0.08963585]]


# Graphs

In [23]:
tf.get_default_graph()

# Variable

In [24]:
temp5 = tf.random_normal((4,4),mean=3,stddev=1)

In [26]:
temp6 = tf.Variable(initial_value=temp5)

## Variables -----> Initial Variables

In [39]:
init = tf.global_variables_initializer()

In [40]:
with tf.Session() as sess:
    sess.run(init)
    sess.run(temp6)